site_name: GD Docs

repo_url: https://github.com/TrigamDev/gd-docs
repo_name: TrigamDev/gd-docs
edit_uri: edit/main/docs

nav:
    - Home: index.md
    - About: about.md
    - Community Projects: community.md
    - Server:
        - Resources:
            - User: server/resources/user.md
        - Topics:
            - Error Codes: server/topics/error.md
        - Endpoints:
            - User:
                - Get User Info: server/endpoints/user/getGJUserInfo20.md
                - Get Profile Comments: server/endpoints/user/getGJAccountComments20.md
                - Get Comment History: server/endpoints/user/getGJCommentHistory.md
                - Get Friend Requests: server/endpoints/user/getGJFriendRequests.md
                - Get User List: server/endpoints/user/getGJUserList20.md
                - Update User Score: server/endpoints/user/updateGJUserScore22.md
    - Client:
        - Resources:
            - Gamesave: client/resources/gamesave.md
        - Topics:
            - Shop: client/topics/shop.md


theme:
    name: material
    icon:
        repo: fontawesome/brands/github
    palette:
        scheme: slate
        primary: indigo
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.tracking
        - navigation.sections
        - navigation.indexed
        - toc.follow
        - content.code.copy
        - content.code.annotate

plugins:
    - git-revision-date-localized:
        enable_creation_date: true
    - git-committers:
        repository: TrigamDev/gd-docs
        branch: main
    - search

markdown_extensions:
    - tables
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - pymdownx.superfences