site_name: GD Docs
site_url: https://trigamdev.github.io/gd-docs

repo_url: https://github.com/TrigamDev/gd-docs
repo_name: TrigamDev/gd-docs
edit_uri: edit/main/docs

nav:
    - Home: index.md
    - About: about.md
    - Community Projects: community.md
    - Server:
        - Resources:
            - User: server/resources/user.md
        - Endpoints:
            - Users:
                - Get User Info: server/endpoints/users/getGJUserInfo20.md
            - Levels:
                - Event:
                    - Get Daily Level: server/endpoints/levels/event/getGJDailyLevel.md
    - Encoding:
        - GJP: encoding/gjp.md
        - UDID: encoding/udid.md

theme:
    name: material
    icon:
        repo: fontawesome/brands/github
    palette:
        scheme: slate
        primary: indigo
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.tracking
        - navigation.sections
        - navigation.indexed
        - toc.follow
        - content.code.copy
        - content.code.annotate
        - content.action.edit
        - content.tabs.link

plugins:
    - git-revision-date-localized:
        enable_creation_date: true
    - git-committers:
        enabled: false
        repository: TrigamDev/gd-docs
        branch: main
        token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
    - search
    - site-urls

markdown_extensions:
    - tables
    - admonition
    - pymdownx.highlight:
        anchor_linenums: true
        use_pygments: false
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
    - './scripts/config.js'
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css