site_name: GD Docs
site_url: https://trigamdev.github.io/gd-docs

repo_url: https://github.com/TrigamDev/gd-docs
repo_name: TrigamDev/gd-docs
edit_uri: edit/main/docs

nav:
    - Home: index.md
    - About: about.md
    - Community Projects: community.md
    - Server:
        - Resources:
            - User: server/resources/user.md
        - Topics:
            - Error Codes: server/topics/error.md
        - Endpoints:
            - Users:
                - Search Users: server/endpoints/users/getGJUsers20.md
                - Get User Info: server/endpoints/users/getGJUserInfo20.md
                - Get Profile Comments: server/endpoints/users/getGJAccountComments20.md
                - Get Comment History: server/endpoints/users/getGJCommentHistory.md
                - Get Friend Requests: server/endpoints/users/getGJFriendRequests20.md
                - Get User List: server/endpoints/users/getGJUserList20.md
                - Update User Score: server/endpoints/users/updateGJUserScore22.md
            - Levels:
                - Search Levels: server/endpoints/levels/getGJLevels21.md
                - Get Level Info: server/endpoints/levels/downloadGJLevel22.md
                - Get Level Comments: server/endpoints/levels/getGJComments21.md
                - Get Level Leaderboard: server/endpoints/levels/getGJLevelScores211.md
                - Get Song Info: server/endpoints/levels/getGJSongInfo.md
            - Lists:
                - Get List Info: server/endpoints/lists/getGJLevelList.md
    - Client:
        - Resources:
            - Gamesave: client/resources/gamesave.md
        - Topics:
            - Shop: client/topics/shop.md
    - Encoding:
        - GJP: encoding/gjp.md


theme:
    name: material
    icon:
        repo: fontawesome/brands/github
    palette:
        scheme: slate
        primary: indigo
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.tracking
        - navigation.sections
        - navigation.indexed
        - toc.follow
        - content.code.copy
        - content.code.annotate
        - content.action.edit
        - content.tabs.link

plugins:
    - git-revision-date-localized:
        enable_creation_date: true
    - git-committers:
        enabled: false
        repository: TrigamDev/gd-docs
        branch: main
        token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
    - search

markdown_extensions:
    - tables
    - admonition
    - pymdownx.highlight:
        anchor_linenums: true
        use_pygments: false
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - './scripts/config.js'
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css
